name: Deploy on Production 

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:

    name: Build, push, and deploy
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout master
      uses: actions/checkout@v2

    - uses: superfly/flyctl-actions/setup-flyctl@master
    - run: |
        flyctl deploy --remote-only
      env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
